development:
  adapter: redis
  url: rredis://localhost:6379/1

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sistema_en_linea_production
