development:
  adapter: redis
  url: redis://redis.104.131.40.8.com:6379

test:
  adapter: redis
  url: redis://redis.104.131.40.8.com:6379

production:
  adapter: redis
  url: redis://redis.104.131.40.8.com:6379
  channel_prefix: sistema_en_linea_production
